### ISSUE TITLE
Media key support?

### ISSUE THREAD

**Issue by orschiro** [mashlol/PlayTube#2]
Dear @mashlol,

Thank you for your great work!

It it possible to control PlayTube using the keyboard media keys?

Thankfully,

Robert

**Comment by mashlol** [comment]
The media keys should already control PlayTube.  It seems to be working for me, let me know if you're having problems with it.

**Comment by orschiro** [comment]
Interesting. For me, they are not working. 

I'm using Chromium 45, Ubuntu 15.04 and PlayTube on a Thinkpad X230. 

Using `Fn+F11` pauses sound in other music applications but not in PlayTube.

**Comment by mashlol** [comment]
Could you try with all other music applications closed & with Chrome as the focused window?

**Comment by orschiro** [comment]
I tried it but without success. 

I even changed the shortcuts from `In Chrome` to `Global`.

Hmmm....

Do you have any other ideas?

![image](https://cloud.githubusercontent.com/assets/170947/10709948/bb559c64-7a41-11e5-9742-30c2d0e2a070.png)

**Comment by mashlol** [comment]
Could you try making them a different key combination and seeing if that will work?  I feel like some other application may be interfering with your media hotkeys.

**Comment by orschiro** [comment]
@mashlol,

You're right. Other shortcuts work well. I will have to check myself how Ubuntu is interfering with the commands. Thanks for the hint!

~ Robert
